# Site settings
title: Japho Blog
SEOTitle: Japho Blog
header-img: img/home-bg.jpg
email: japhoo@163.com
description: "The shortest answer is doing."
keyword: "Japho, Japho Blog, Japho的博客, iOS, Apple, iPhone"
url: "http://japho.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "hhttps://github.com/japho/japho.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The shortest answer is doing."
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     wangjifeng1114
zhihu_username:     japho
github_username:    japho
# facebook_username:  baiying.qiu.7
jianshu_username:   a1d80b6eaa9e
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 440847f85c950402a76b                            #生成的clientID
  clientSecret: 92371c89905e71fe83cfd3815f779358726d9c48    #生成的clientSecret
  repo: japho.github.io    #仓库名称
  owner: japho    #github用户名
  admin: japho
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-128251504-1'            # Format: UA-xxxxxx-xx
ga_domain: japho.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·Japho",
        href: "https://www.jianshu.com/u/a1d80b6eaa9e"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    },{
        title: "Google Analytics",
        href: "https://analytics.google.com"
    }
]
